# Generated by Django 2.2.12 on 2020-04-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpManager',
            fields=[
                ('mg_id', models.AutoField(primary_key=True, serialize=False)),
                ('mag_name', models.CharField(max_length=32)),
                ('mg_pwd', models.CharField(max_length=64)),
                ('mg_time', models.PositiveIntegerField()),
                ('role_id', models.IntegerField()),
                ('mg_mobile', models.CharField(blank=True, max_length=32, null=True)),
                ('mg_email', models.CharField(blank=True, max_length=64, null=True)),
                ('mg_state', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'sp_manager',
            },
        ),
    ]
