# Generated by Django 2.2.12 on 2020-04-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpPermission',
            fields=[
                ('ps_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('ps_name', models.CharField(max_length=20)),
                ('ps_pid', models.PositiveSmallIntegerField()),
                ('ps_c', models.CharField(max_length=32)),
                ('ps_a', models.CharField(max_length=32)),
                ('ps_level', models.CharField(max_length=1)),
            ],
            options={
                'managed': False,
                'db_table': 'sp_permission',
            },
        ),
        migrations.CreateModel(
            name='SpPermissionApi',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('ps_api_service', models.CharField(blank=True, max_length=255, null=True)),
                ('ps_api_action', models.CharField(blank=True, max_length=255, null=True)),
                ('ps_api_path', models.CharField(blank=True, max_length=255, null=True)),
                ('ps_api_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'sp_permission_api',
            },
        ),
        migrations.CreateModel(
            name='SpRole',
            fields=[
                ('role_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=20)),
                ('ps_ids', models.CharField(max_length=512)),
                ('ps_ca', models.TextField(blank=True, null=True)),
                ('role_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'sp_role',
            },
        ),
    ]
